version: '3'

services:
  db:
    image: postgres:12.14-alpine
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: reservation
    ports:
      - "5432:5432"

    restart: always
    ports:
      - "6379:6379"
