server:
  port: 8080
  servlet:
    context-path: /reservation

spring:
  application:
    name: RoomReservation
  output:
    ansi:
      enabled: always

  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  datasource:
    username: postgres
    password: postgres123
    url: jdbc:postgresql://localhost:5432/reservation
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
