server:
  port: 8080
  servlet:
    context-path: /reservation

spring:
  application:
    name: RoomReservation
  output:
    ansi:
      enabled: always

  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE-URL}
    

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
